
project_id = "vrngwrqfbwfteqzmvppo"

[functions.get-admin-users]
verify_jwt = true

[functions.get-user-by-id]
verify_jwt = true

[functions.update-admin-email]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

[functions.admin-user-operations]
verify_jwt = true
